### ISSUE TITLE
My own notes do not appear

### ISSUE THREAD

**Issue by DublinBen** [CrustyJew/SnooNotes#11]
I am running version 0.0.7.1

I can view notes that have been left by other mods, and record my own.  I can't read my own notes.  They never appear, and the box does not show up.  The notes are visible to other mods.

**Comment by CrustyJew** [comment]
What browser and browser version are you using?

Also have you tried hitting the "Refresh Snoonotes" button in the options panel?

**Comment by bencook** [comment]
I'm running Firefox 38.6.1.  I've hit the Refresh Snoonotes a couple times.

**Comment by DublinBen** [comment]
Logged into the wrong account by accident.  I'd appreciate if you would edit your comment to remove that confusion.  I will upgrade my browser to the latest version and try again.

**Comment by CrustyJew** [comment]
There we go. And let me know if that doesn't fix the problem. I need to write some more debug code into this so it's easier to troubleshoot.

**Comment by DublinBen** [comment]
I've updated to Firefox version 45.0 and I'm still unable to read my own notes.

**Comment by CrustyJew** [comment]
Alright, can you try using a second person/account and viewing the same comment in each account. Add a note with one, and see if it shows up in the other? It sounds like your browser isn't connecting to the update server for some reason. Are you running any other extensions as well that might be interfering?
