### ISSUE TITLE
Fix the updater for Firefox users

### ISSUE THREAD

**Issue by ChiyoOsaka** [CrustyJew/SnooNotes#2]
Because of Mozilla things, in order to update, you need to reinstall the app.

It would be nice if it was updated using the same method as Chrome.

**Comment by CrustyJew** [comment]
Yeah this has to do with how Mozilla is changing addons to require them being signed. It's been in the queue for like 3 months now.. I might switch it to self hosted and hope that speeds things up.

**Comment by CrustyJew** [comment]
Addon located here now: https://addons.mozilla.org/en-US/firefox/addon/snoonotes/?src=api
