### ISSUE TITLE
Request to be able to sort newest notes to the top

### ISSUE THREAD

**Issue by hacksoncode** [CrustyJew/SnooNotes#33]
Some of our (changemyview) mods have gotten confused a few times because the toolbox import put the most recent notes at the top, but snoo notes adds them to the bottom.

Also... after a long time people's notes list can get long making it inconvenient to scroll down to the most recent notes.

Could we get it to sort by date, descending? As an option if necessary (though I suspect that's probably what everyone always wants).

**Comment by CrustyJew** [comment]
I'll look in to adding some options for this.

**Comment by hacksoncode** [comment]
Thanks much!

**Comment by CrustyJew** [comment]
This got added in a while ago. Closing issue. Enjoy!
